<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 scene.gltf
Author: artemycz (https://sketchfab.com/artemycz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/falcon-9-spacex-rocket-58784d6b55ad47d2985f353459759f06
Title: Falcon 9 SpaceX rocket
-->

<script>
	import { T } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import { Tween } from 'svelte/motion';
	import { activeSection } from '../../../../stores/stores';
	import { linear } from 'svelte/easing';

	let { fallback, error, children, ref = $bindable(), ...props } = $props();

	const gltf = useGltf('/models/falcon9/scene.gltf');

	const payloadOriginalPosition = [0, 0, 8.48];
	const tweenOptions = { duration: 5000, easing: linear };
	const payloadPosX = new Tween(payloadOriginalPosition[0], tweenOptions);
	const payloadPosY = new Tween(payloadOriginalPosition[1], tweenOptions);
	const payloadPosZ = new Tween(payloadOriginalPosition[2], tweenOptions);

	$effect(() => {
		if ($activeSection === 4) {
			// payloadPosX.set(payloadPosX.current + 10);
			payloadPosZ.set(payloadPosZ.current + 20);
			// payloadPosZ.set(payloadPosX.current + 10);
		} else {
			// payloadPosX.set(payloadOriginalPosition[0]);
			payloadPosZ.set(payloadOriginalPosition[2]);
			// payloadPosZ.set(payloadOriginalPosition[2]);
		}
	});
</script>

<T.Group castShadow bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group castShadow rotation={[-Math.PI / 2, 0, 0]} scale={259.92}>
			<T.Group castShadow position={[0, 0, 0.24]} scale={0.38}>
				<T.Mesh
					castShadow
					geometry={gltf.nodes.Cylinder_body_0.geometry}
					material={gltf.materials.body}
				/>
				<T.Mesh
					castShadow
					geometry={gltf.nodes.Cylinder_body_black_0.geometry}
					material={gltf.materials.body_black}
				/>
			</T.Group>
			<T.Mesh
				castShadow
				geometry={gltf.nodes.Plane016_details_0.geometry}
				material={gltf.materials.details}
				position={[0, 0, 7.07]}
				rotation={[0, 1.55, 1.57]}
				scale={0.38}
			/>
			<T.Mesh
				castShadow
				geometry={gltf.nodes.Plane015_details_0.geometry}
				material={gltf.materials.details}
				position={[0, 0, 7.07]}
				rotation={[0, 1.55, 1.57]}
				scale={0.38}
			/>
			<T.Mesh
				castShadow
				geometry={gltf.nodes.Plane014_details_0.geometry}
				material={gltf.materials.details}
				position={[0, -0.29, 7.07]}
				rotation={[0, 1.55, 1.57]}
				scale={0.38}
			/>
			<T.Mesh
				castShadow
				geometry={gltf.nodes.Circle009_engine_0.geometry}
				material={gltf.materials.engine}
				position={[0, 0, 0.19]}
				rotation={[-Math.PI, 0, 0]}
				scale={0.38}
			/>
			<T.Mesh
				castShadow
				geometry={gltf.nodes.Circle008_engine_0.geometry}
				material={gltf.materials.engine}
				position={[0, 0, 0.19]}
				rotation={[-Math.PI, 0, 0]}
				scale={0.38}
			/>
			<T.Mesh
				castShadow
				geometry={gltf.nodes.Circle007_engine_0.geometry}
				material={gltf.materials.engine}
				position={[0, 0, 0.19]}
				rotation={[-Math.PI, 0, 0]}
				scale={0.38}
			/>
			<T.Mesh
				castShadow
				geometry={gltf.nodes.Circle006_engine_0.geometry}
				material={gltf.materials.engine}
				position={[0, 0, 0.19]}
				rotation={[-Math.PI, 0, 0]}
				scale={0.38}
			/>
			<T.Mesh
				castShadow
				geometry={gltf.nodes.Circle005_engine_0.geometry}
				material={gltf.materials.engine}
				position={[0, 0, 0.19]}
				rotation={[-Math.PI, 0, 0]}
				scale={0.38}
			/>
			<T.Mesh
				castShadow
				geometry={gltf.nodes.Circle004_engine_0.geometry}
				material={gltf.materials.engine}
				position={[0, 0, 0.19]}
				rotation={[-Math.PI, 0, 0]}
				scale={0.38}
			/>
			<T.Mesh
				castShadow
				geometry={gltf.nodes.Circle003_engine_0.geometry}
				material={gltf.materials.engine}
				position={[0, 0, 0.19]}
				rotation={[-Math.PI, 0, 0]}
				scale={0.38}
			/>
			<T.Mesh
				castShadow
				geometry={gltf.nodes.Circle002_engine_0.geometry}
				material={gltf.materials.engine}
				position={[0, 0, 0.19]}
				rotation={[-Math.PI, 0, 0]}
				scale={0.38}
			/>
			<T.Mesh
				castShadow
				geometry={gltf.nodes.Circle001_engine_0.geometry}
				material={gltf.materials.engine}
				position={[0, 0, 0.19]}
				rotation={[-Math.PI, 0, 0]}
				scale={0.38}
			/>
			<T.Mesh
				castShadow
				geometry={gltf.nodes.Plane013_legs_0.geometry}
				material={gltf.materials.legs}
				position={[0.19, 0.25, 1.01]}
				rotation={[-Math.PI / 2, -0.84, -Math.PI]}
				scale={[0.02, 0.03, 0.03]}
			/>
			<T.Mesh
				castShadow
				geometry={gltf.nodes.Plane012_legs_0.geometry}
				material={gltf.materials.legs}
				position={[0.22, -0.18, 1.01]}
				rotation={[-Math.PI / 2, -0.84, -Math.PI]}
				scale={[0.02, 0.03, 0.03]}
			/>
			<T.Mesh
				castShadow
				geometry={gltf.nodes.Plane011_legs_0.geometry}
				material={gltf.materials.legs}
				position={[-0.2, -0.21, 1.01]}
				scale={0.38}
			/>
			<T.Mesh
				castShadow
				geometry={gltf.nodes.Plane009_legs_0.geometry}
				material={gltf.materials.legs}
				position={[0, 0.03, 1.01]}
				rotation={[-Math.PI / 2, -0.84, -Math.PI]}
				scale={[0.02, 0.03, 0.03]}
			/>
			<T.Mesh
				castShadow
				geometry={gltf.nodes.Plane008_details_0.geometry}
				material={gltf.materials.details}
				position={[-0.02, 0.26, 7.87]}
				rotation={[-Math.PI / 2, 0, Math.PI]}
				scale={0.01}
			/>
			<T.Mesh
				castShadow
				geometry={gltf.nodes.Plane007_details_0.geometry}
				material={gltf.materials.details}
				position={[0.27, -0.01, 8.14]}
				rotation={[Math.PI / 2, 1.48, 0]}
				scale={0.01}
			/>
			<T.Mesh
				castShadow
				geometry={gltf.nodes.Plane006_details_0.geometry}
				material={gltf.materials.details}
				position={[0.27, -0.01, 7.64]}
				rotation={[Math.PI / 2, 1.48, 0]}
				scale={0.01}
			/>
			<T.Mesh
				castShadow
				geometry={gltf.nodes.Plane005_details_0.geometry}
				material={gltf.materials.details}
				position={[-0.25, -0.1, 7.55]}
				rotation={[Math.PI / 2, -1.14, 0]}
				scale={0.01}
			/>
			<T.Mesh
				castShadow
				geometry={gltf.nodes.Plane004_details_0.geometry}
				material={gltf.materials.details}
				position={[-0.02, -0.27, 7.49]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={0.01}
			/>
			<T.Mesh
				castShadow
				geometry={gltf.nodes.Plane003_details_0.geometry}
				material={gltf.materials.details}
				position={[-0.19, -0.19, 8.12]}
				rotation={[-Math.PI / 2, 0.78, 0]}
				scale={[-0.01, 0.01, 0.01]}
			/>
			<T.Mesh
				castShadow
				geometry={gltf.nodes.Plane_details_0.geometry}
				material={gltf.materials.details}
				position={[0.09, -0.26, 7.2]}
				rotation={[-Math.PI / 2, -0.3, 0]}
				scale={[-0.01, 0.01, 0.01]}
			/>
			<T.Mesh
				castShadow
				geometry={gltf.nodes.Cube002_details_0.geometry}
				material={gltf.materials.details}
				position={[0, -0.27, 7.27]}
				scale={[0.01, 0, 0.01]}
			/>
			<T.Mesh
				castShadow
				geometry={gltf.nodes.Plane002_details_0.geometry}
				material={gltf.materials.details}
				position={[0, 0, 7.07]}
				rotation={[0, 1.55, 1.57]}
				scale={0.38}
			/>
			<T.Mesh
				castShadow
				geometry={gltf.nodes.Cube_details_0.geometry}
				material={gltf.materials.details}
				position={[0, 0, 6.01]}
				rotation={[-0.06, 0, 0]}
				scale={0.01}
			/>
			<T.Mesh
				castShadow
				geometry={gltf.nodes.Cube004_fins_0.geometry}
				material={gltf.materials.fins}
				position={[0, 0, 5.93]}
				rotation={[0, 0, Math.PI / 4]}
				scale={0.38}
			/>
			<T.Mesh
				castShadow
				geometry={gltf.nodes.Circle_body_black_0.geometry}
				material={gltf.materials.body_black}
				position={[0, 0, 0.19]}
				rotation={[-Math.PI, 0, 0]}
				scale={0.38}
			/>
			<T.Mesh
				castShadow
				geometry={gltf.nodes.Cylinder001_fairing_0.geometry}
				material={gltf.materials.fairing}
				position={[payloadPosX.current, payloadPosY.current, payloadPosZ.current]}
				rotation={[0, 0, Math.PI / 2]}
				scale={0.38}
			/>
			<T.PointLight color="hsl(120,100%,50%)" intensity={5} position={[0, 0, 8.48]} />
			<T.Mesh
				castShadow
				geometry={gltf.nodes.Plane010_legs_0.geometry}
				material={gltf.materials.legs}
				position={[-0.01, 0.02, 0.75]}
				rotation={[-1.72, -0.15, -0.05]}
				scale={[-0.01, 0.01, 0.01]}
			/>
			<T.PointLight color="hsl(220,100%,50%)" intensity={5} />
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
