<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 strongback.gltf
Author: Thor's Hammer (https://sketchfab.com/captaintokra)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spacex-falcon-9-strongback-854921c608784624ad2af042a24fded4
Title: SpaceX Falcon 9 Strongback
-->

<script>
	import { T } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	let { fallback, error, children, ref = $bindable(), ...props } = $props();

	const gltf = useGltf('/models/strongback/strongback.gltf');
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh
			castShadow
			geometry={gltf.nodes.Object_2.geometry}
			rotation={[-Math.PI, 0, Math.PI]}
			scale={0.34}
		>
			<!-- material={gltf.materials['Scene_-_Root']} -->
			<T.MeshStandardMaterial color="hsl(220,10%,80%)" />
		</T.Mesh>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
